[cp1] fb-02 shapoval
ipt-labs/crypto-22-23 pull request #15
Opened 2022-09-22 15:43 UTC by fb02-hs

2022-09-27 20:09 UTC, ipt-labs commented
цей пр треба переробити - ви зносите папки і файли інших студентів

2022-09-28 06:36 UTC, fb02-hs commented
> 

Виправилось?

2022-09-28 20:15 UTC, ipt-labs commented
ні, досі видаляються всі чужі роботи 
<img width="359" alt="Снимок экрана 2022-09-28 в 23 13 55" src="https://user-images.githubusercontent.com/90145193/192879869-6bd13a4c-94f7-4133-bfed-b4670a8114ca.png">

2022-09-28 20:16 UTC, ipt-labs requested changes
pr not ok

2022-09-29 05:50 UTC, closed without merging