[CP-1] Degtarov (FB-05)
ipt-labs/crypto-22-23 pull request #33
Opened 2022-09-29 16:02 UTC by degtarov-fb05

2022-10-02 16:31 UTC, ipt-labs requested changes
із рожевою програмкою очікувалось ваше осмислене вгадування: прочитати початок фрази, вгадувати наступну букву, приймаючи до уваги прочитане

2022-10-02 16:31 UTC, ipt-labs commented on cp1/degtarov_fb-05_cp1/lab1.py
> +        dictonary.update({l:round(dictonary[l]/len(txt),5)})
краще округлювати після всіх проведених обчислень, щоб не втрачати точність

2022-10-02 16:31 UTC, ipt-labs commented on cp1/degtarov_fb-05_cp1/lab1.py
> +            txt += "а"
що це ?

2022-10-02 16:31 UTC, ipt-labs commented on cp1/degtarov_fb-05_cp1/lab1.py
> +    file = open('1.txt',encoding='utf8')
є класна штука - контекстний менеджер, який за вас буде слідкувати за дескриптором файлу, закривати його після використання - 
with open(..) as f: ...

2022-10-02 16:31 UTC, ipt-labs commented on cp1/degtarov_fb-05_cp1/lab1.py
> +    a11=pd.DataFrame(vva.reshape((34,34)),index=f1.keys(),columns=f1.keys())
краще не мати магічних чисел в коді

2022-10-02 16:31 UTC, merged

2022-11-10 10:40 UTC, degtarov-fb05 commented on cp1/degtarov_fb-05_cp1/lab1.py
> +        dictonary.update({l:round(dictonary[l]/len(txt),5)})
> із рожевою програмкою очікувалось ваше осмислене вгадування: прочитати початок фрази, вгадувати наступну букву, приймаючи до уваги прочитане

Так я це вже зрозумів коли першу частину закінчував (нажаль). Але потім вже робив як треба

2022-11-10 10:43 UTC, degtarov-fb05 commented on cp1/degtarov_fb-05_cp1/lab1.py
> +        dictonary.update({l:round(dictonary[l]/len(txt),5)})
> краще округлювати після всіх проведених обчислень, щоб не втрачати точність

Дякую за пораду :) Просто я тут хотів спочатку заповнити статистику а потім розрахунок частоти

2022-11-10 10:48 UTC, degtarov-fb05 commented on cp1/degtarov_fb-05_cp1/lab1.py
> +            txt += "а"
Спочатку хотів для  розрахунку Н1 (зчитувати і визначити), а потім для розрахунку Н2. А саме це (txt += "а") хотів зробити щоб кожній літері була пара. Якщо не складно то можете дати пораду як це коректніше зробити.

2022-11-10 10:51 UTC, degtarov-fb05 commented on cp1/degtarov_fb-05_cp1/lab1.py
> +    file = open('1.txt',encoding='utf8')
Дякую за пораду, подивлюсь і прочитаю про цей менеджер

2022-11-10 10:52 UTC, degtarov-fb05 commented on cp1/degtarov_fb-05_cp1/lab1.py
> +    a11=pd.DataFrame(vva.reshape((34,34)),index=f1.keys(),columns=f1.keys())
Просто хотів  створити датафрем і занести в файл