second commit
ipt-labs/crypto-22-23 pull request #63
Opened 2022-10-07 19:33 UTC by bitweal

2022-10-12 18:52 UTC, ipt-labs requested changes
додайте протокол в пдф будь ласка

2022-10-12 19:03 UTC, bitweal commented
додав

ср, 12 жовт. 2022 р. о 21:52 ipt-labs ***@***.***> пише:

> ***@***.**** requested changes on this pull request.
>
> додайте протокол в пдф будь ласка
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/ipt-labs/crypto-22-23/pull/63#pullrequestreview-1139572974>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AWMWA5MUZXYQX7FSSGWSSTTWC4CHRANCNFSM6AAAAAAQ73RYDQ>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-10-13 08:43 UTC, ipt-labs requested changes
для рожевої програми очікувалось, що ви читаєте текст і намагаєтесь вгадати наступну букву опираючись на прочитане.
не бачу як ви застосовуєте 2 різних способи "читання" біграм (перехресні-неперехресні чи "х кроком 1 - з кроком 2")

2022-10-13 08:57 UTC, bitweal commented
не можу чомусь додати...
зараз перейменю файлик .py

чт, 13 жовт. 2022 р. о 11:43 ipt-labs ***@***.***> пише:

> ***@***.**** requested changes on this pull request.
>
> для рожевої програми очікувалось, що ви читаєте текст і намагаєтесь
> вгадати наступну букву опираючись на прочитане.
> не бачу як ви застосовуєте 2 різних способи "читання" біграм
> (перехресні-неперехресні чи "х кроком 1 - з кроком 2")
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/ipt-labs/crypto-22-23/pull/63#pullrequestreview-1140337901>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AWMWA5NCVSZZTGRNYDWYLO3WC7DTRANCNFSM6AAAAAAQ73RYDQ>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-10-13 09:04 UTC, bitweal commented
щось я в git не розумію що до чого, вийшло чи ні...

чт, 13 жовт. 2022 р. о 11:57 Андрій Чирков ***@***.***> пише:

> не можу чомусь додати...
> зараз перейменю файлик .py
>
> чт, 13 жовт. 2022 р. о 11:43 ipt-labs ***@***.***> пише:
>
>> ***@***.**** requested changes on this pull request.
>>
>> для рожевої програми очікувалось, що ви читаєте текст і намагаєтесь
>> вгадати наступну букву опираючись на прочитане.
>> не бачу як ви застосовуєте 2 різних способи "читання" біграм
>> (перехресні-неперехресні чи "х кроком 1 - з кроком 2")
>>
>> —
>> Reply to this email directly, view it on GitHub
>> <https://github.com/ipt-labs/crypto-22-23/pull/63#pullrequestreview-1140337901>,
>> or unsubscribe
>> <https://github.com/notifications/unsubscribe-auth/AWMWA5NCVSZZTGRNYDWYLO3WC7DTRANCNFSM6AAAAAAQ73RYDQ>
>> .
>> You are receiving this because you authored the thread.Message ID:
>> ***@***.***>
>>
>

2022-10-13 09:06 UTC, bitweal commented
аааа додалось, начебто добре все

чт, 13 жовт. 2022 р. о 12:03 Андрій Чирков ***@***.***> пише:

> щось я в git не розумію що до чого, вийшло чи ні...
>
> чт, 13 жовт. 2022 р. о 11:57 Андрій Чирков ***@***.***> пише:
>
>> не можу чомусь додати...
>> зараз перейменю файлик .py
>>
>> чт, 13 жовт. 2022 р. о 11:43 ipt-labs ***@***.***> пише:
>>
>>> ***@***.**** requested changes on this pull request.
>>>
>>> для рожевої програми очікувалось, що ви читаєте текст і намагаєтесь
>>> вгадати наступну букву опираючись на прочитане.
>>> не бачу як ви застосовуєте 2 різних способи "читання" біграм
>>> (перехресні-неперехресні чи "х кроком 1 - з кроком 2")
>>>
>>> —
>>> Reply to this email directly, view it on GitHub
>>> <https://github.com/ipt-labs/crypto-22-23/pull/63#pullrequestreview-1140337901>,
>>> or unsubscribe
>>> <https://github.com/notifications/unsubscribe-auth/AWMWA5NCVSZZTGRNYDWYLO3WC7DTRANCNFSM6AAAAAAQ73RYDQ>
>>> .
>>> You are receiving this because you authored the thread.Message ID:
>>> ***@***.***>
>>>
>>

2022-10-13 11:18 UTC, merged